kind: Deployment
apiVersion: apps/v1

metadata:
  name: website

spec:
  template:
    spec:
      containers:
        - name: website
          env:
            - name: NODE_ENV
              value: production
