version: '3'

services:
  website:
    build:
      context: .
      dockerfile: docker_dev/Dockerfile.mac
    image: hubrise/website-dev
    volumes:
      - website-sync:/var/www/website
    ports:
      - "8000:8000"

volumes:
  website-sync:
    external: true