kind: Deployment
apiVersion: apps/v1

metadata:
  name: website

spec:
  replicas: 1

  template:
    metadata:
      annotations:
        # Change value to force pod restart
        checksum/config: ""

    spec:
      containers:
        - name: website
          # We use the ":latest" image
          imagePullPolicy: Always

          resources:
            requests:
              cpu: 30m
              memory: 80Mi
            limits:
              cpu: 50m
              memory: 150Mi
          env:
            - name: SENTRY_DSN
              value: https://96b4d1defd7648308c6e30f8a3470cfd@sentry.io/1776244
            - name: RECAPTCHA_SITE_KEY
              value: 6LfjbNYUAAAAAPx_tCv_YyhueK2JIjf58b2HGU8d
