kind: Deployment
apiVersion: apps/v1

metadata:
  name: website

spec:
  replicas: 2

  template:
    spec:
      containers:
        - name: website
          # We use the ":latest" image
          imagePullPolicy: Always

          env:
            - name: NO_INDEX
              value: "true"

          resources:
            requests:
              cpu: 300m
              memory: 750Mi
            limits:
              # We need some CPU for short periods of time after startup, when optimised images are not yet cached.
              cpu: 1000m
              memory: 1500Mi
