name: eslint

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run eslint

    container:
      image: node:18.16.0-bookworm

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install JS dependencies
        run: yarn install

      - name: Run linter
        run: yarn eslint
