name: eslint

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run eslint
    env:
      NODE_ENV: development

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Node.js and package cache
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
          cache: 'yarn'

      - name: Install JS dependencies
        run: yarn install

      - name: Run linter
        run: yarn eslint
